name: Commitlint

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]

concurrency:
  group: commitlint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commitlint:
    uses: Hexalith/Hexalith.Builds/.github/workflows/commitlint.yml@main
    with:
      pull-request-title: ${{ github.event.pull_request.title }}
